version: "2"
linters:
  enable:
    - errorlint
    - exhaustive
    - goconst
    - godot
    - goprintffuncname
    - makezero
    - nilerr
    - prealloc
    - thelper
    - unconvert
    - unparam
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - goimports
