# Example ThriftCheck Configuration File

# List of paths that will be be used for `include` directives. Relative paths
# are resolved relative to the current working directory.
#
# Note that if  any -I options are specified on the command line, they will
# be used instead of this configuration value.
includes = [
    "shared",
]

# Lists of checks to explicitly enable or disable. If a prefix is given (e.g.
# "namespace"), all checks matching that prefix will be matched.
[checks]
enabled = []
disabled = []

# Configuration values for specific checks:

[checks.enum]
[checks.enum.size]
warning = 500
error = 1000

[checks.include]
[[checks.include.restricted]]
"*" = "(huge|massive).thrift"

[checks.map]
[checks.map.value]
# Restrict specific types as map values to enforce coding standards
# Common examples:
# - ["map"] to disallow nested maps
# - ["union"] to prevent unions as map values
# - ["union", "map"] to restrict both
restricted = [
    "union",  # Disallow unions as map values
    "map",    # Disallow nested maps
    "string", # Disallow string as map values
]

[checks.names]
reserved = [
    "template",
]

[checks.namespace]
[[checks.namespace.patterns]]
py = "^idl\\."